<?php if($block->canShow()):?>
    <?php if ($block->showImageAboveTitle()): ?>    
        <a href="<?php echo $block->getUrlCreditea(); ?>" data-vbtype="iframe" data-customclass="popup-creditea" class="creditea-click">
            <img src="<?= $block->getViewFileUrl('Creditea_Magento2::images/promo/CrediteaPay_Promo1.png') ?>" alt="Promo Image Above Title" />
        </a>
        <script>require(['jquery', 'creditea-venobox'], function($){$('a.creditea-click').venobox();});</script>
    <?php endif; ?>
<?php endif; ?>