<?php if($block->canShow()):?>
    <?php if ($block->showImageBelowDescription()): ?>
        <a href="<?php echo $block->getUrlCreditea(); ?>" data-vbtype="iframe" data-customclass="popup-creditea" class="creditea-click">
            <img src="<?= $block->getBannerUrl() ?>" alt="Promo Image Below Description" />
        </a>
        <script>require(['jquery', 'creditea-venobox'], function($){$('a.creditea-click').venobox();});</script>
    <?php endif; ?>
<?php endif; ?>