<?php if($block->canShow(true) && true == false):?>
    <a href="#" data-customclass="popup-creditea" class="creditea-promo-modal creditea-checkout-promo">
        <img src="<?= $block->getBannerUrl() ?>" alt="Promo Image Under Checkout Summary" />
    </a>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var crediteaPromo = document.querySelector('.creditea-checkout-promo');
            var sidebar = document.querySelector('aside.opc-sidebar');

            if (crediteaPromo && sidebar) {
                sidebar.appendChild(crediteaPromo);
            }
        });
    </script>
<?php endif; ?>