<style>
    div.product.media{
        position: relative;
    }
    .creditea-badge-overlay {
        position: absolute;
        top: 5px;
        right: 5px;
        width: 60px;
        z-index: 5;
    }
</style>
<?php if($block->canShow()):?>
    <?php if ($block->showBadgeOverlay()): ?>
        <div class="creditea-badge-overlay">
            <img src="<?= $block->getViewFileUrl('Creditea_Magento2::images/promo/CrediteaPay_Promo5.png') ?>" alt="Creditea Product Badge" />
        </div>
    <?php endif; ?>
<?php endif; ?>